// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAnVSL6EhU_VoF-h4NuTZJcEtGeKv6cIyk',
    appId: '1:736738794720:web:990bf92499d4c5faafc485',
    messagingSenderId: '736738794720',
    projectId: 'kbookclone',
    authDomain: 'kbookclone.firebaseapp.com',
    storageBucket: 'kbookclone.appspot.com',
    measurementId: 'G-F3JSCE4J71',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAUBRgT3RUzoM-t40rb_bxcf3gDdEANkYo',
    appId: '1:736738794720:android:5bf86fa4c4fe5f24afc485',
    messagingSenderId: '736738794720',
    projectId: 'kbookclone',
    storageBucket: 'kbookclone.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDzNGOfBmAv8OiON4oL4m5Zxl4xHSzxh0U',
    appId: '1:736738794720:ios:46453aceb58211e9afc485',
    messagingSenderId: '736738794720',
    projectId: 'kbookclone',
    storageBucket: 'kbookclone.appspot.com',
    iosBundleId: 'com.example.khatabookclone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDzNGOfBmAv8OiON4oL4m5Zxl4xHSzxh0U',
    appId: '1:736738794720:ios:46453aceb58211e9afc485',
    messagingSenderId: '736738794720',
    projectId: 'kbookclone',
    storageBucket: 'kbookclone.appspot.com',
    iosBundleId: 'com.example.khatabookclone',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAnVSL6EhU_VoF-h4NuTZJcEtGeKv6cIyk',
    appId: '1:736738794720:web:70a8385f92b9d113afc485',
    messagingSenderId: '736738794720',
    projectId: 'kbookclone',
    authDomain: 'kbookclone.firebaseapp.com',
    storageBucket: 'kbookclone.appspot.com',
    measurementId: 'G-MT88WL16RC',
  );
}
